/**
 * Chess Academy Pro — PDF Generator
 * Uses pdfkit for fee invoices and student progress reports
 */
const PDFDocument = require('pdfkit');

// ─── Brand colours ────────────────────────────────────────────────────────────
const AMBER = '#C8961E';
const DARK = '#1C1107';
const MID = '#5C4A38';
const MUTED = '#9B8575';
const BG_LIGHT = '#F7F4EF';
const BORDER = '#E2D8CE';
const GREEN = '#15803D';
const RED = '#DC2626';

function formatCurrency(amount, currency = 'INR') {
    const sym = currency === 'INR' ? '₹' : currency === 'USD' ? '$' : currency;
    return `${sym}${Number(amount || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
}

function formatDate(d) {
    if (!d) return '—';
    return new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
}

// ─── Shared header drawing ────────────────────────────────────────────────────
function drawHeader(doc, academy, title, subtitle) {
    // Background bar
    doc.rect(0, 0, doc.page.width, 80).fill(DARK);

    // Academy name
    doc.fontSize(18).fillColor('#FFFFFF').font('Helvetica-Bold')
        .text(academy?.name || 'Chess Academy', 40, 22, { width: 360 });

    // Document title top-right
    doc.fontSize(11).fillColor(AMBER).font('Helvetica-Bold')
        .text(title, 40, 48, { width: doc.page.width - 80, align: 'right' });

    if (subtitle) {
        doc.fontSize(8).fillColor('#CCBBAA').font('Helvetica')
            .text(subtitle, 40, 62, { width: doc.page.width - 80, align: 'right' });
    }

    // Accent line
    doc.rect(0, 80, doc.page.width, 3).fill(AMBER);
    doc.moveDown(0);
}

function drawFooter(doc, pageNum, totalPages) {
    const y = doc.page.height - 40;
    doc.rect(0, y - 8, doc.page.width, 1).fill(BORDER);
    doc.fontSize(8).fillColor(MUTED).font('Helvetica')
        .text('Generated by Chess Academy Pro', 40, y, { width: 300 })
        .text(`Page ${pageNum} of ${totalPages}`, 40, y, { width: doc.page.width - 80, align: 'right' });
}

function sectionTitle(doc, text, y) {
    doc.rect(40, y, doc.page.width - 80, 22).fill(BG_LIGHT);
    doc.fontSize(9).fillColor(AMBER).font('Helvetica-Bold')
        .text(text.toUpperCase(), 48, y + 6);
    return y + 30;
}

// ─── FEE INVOICE PDF ──────────────────────────────────────────────────────────
async function generateInvoicePDF(invoice, student, academy, batch) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margins: { top: 100, bottom: 60, left: 40, right: 40 } });
        const buffers = [];
        doc.on('data', d => buffers.push(d));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        const W = doc.page.width - 80; // usable width

        // ── Header ──
        drawHeader(doc, academy, 'INVOICE', `# ${invoice.invoice_number}`);

        let y = 100;

        // ── Billed to / From ──
        // Left: billed to
        doc.rect(40, y, W / 2 - 8, 90).fill('#FAFAFA').stroke(BORDER);
        doc.fontSize(8).fillColor(AMBER).font('Helvetica-Bold').text('BILLED TO', 52, y + 10);
        doc.fontSize(11).fillColor(DARK).font('Helvetica-Bold').text(student?.name || '—', 52, y + 24);
        doc.fontSize(9).fillColor(MID).font('Helvetica')
            .text(student?.email || '', 52, y + 40)
            .text(student?.phone ? `Ph: ${student.phone}` : '', 52, y + 54);
        if (batch) {
            doc.fontSize(8).fillColor(MUTED).text(`Batch: ${batch.name}`, 52, y + 68);
        }

        // Right: invoice meta
        const rx = 40 + W / 2 + 8;
        doc.rect(rx, y, W / 2 - 8, 90).fill('#FAFAFA').stroke(BORDER);
        const metaRows = [
            ['Invoice No', invoice.invoice_number],
            ['Issue Date', formatDate(invoice.issued_at)],
            ['Due Date', formatDate(invoice.due_date)],
            ['Period', invoice.period_from ? `${formatDate(invoice.period_from)} – ${formatDate(invoice.period_to)}` : '—'],
            ['Status', (invoice.status || 'draft').toUpperCase()],
        ];
        metaRows.forEach(([label, val], i) => {
            doc.fontSize(8).fillColor(MUTED).font('Helvetica').text(label, rx + 12, y + 10 + i * 16);
            doc.fontSize(8).fillColor(DARK).font('Helvetica-Bold').text(val, rx + 12 + 70, y + 10 + i * 16);
        });

        y += 106;

        // ── Line items table ──
        y = sectionTitle(doc, 'Line Items', y);

        // Table header
        doc.rect(40, y, W, 22).fill(DARK);
        doc.fontSize(8).fillColor('#FFFFFF').font('Helvetica-Bold')
            .text('Description', 52, y + 7)
            .text('Qty', 52 + W * 0.55, y + 7, { width: 40, align: 'right' })
            .text('Rate', 52 + W * 0.65, y + 7, { width: 60, align: 'right' })
            .text('Amount', 52 + W * 0.8, y + 7, { width: W * 0.18, align: 'right' });
        y += 22;

        const items = Array.isArray(invoice.line_items) ? invoice.line_items : [];
        items.forEach((item, idx) => {
            const rowBg = idx % 2 === 0 ? '#FFFFFF' : BG_LIGHT;
            doc.rect(40, y, W, 22).fill(rowBg).stroke(BORDER);
            doc.fontSize(9).fillColor(DARK).font('Helvetica')
                .text(item.description || '—', 52, y + 6, { width: W * 0.52 })
            doc.fontSize(9).fillColor(MID)
                .text(String(item.qty || 1), 52 + W * 0.55, y + 6, { width: 40, align: 'right' })
                .text(formatCurrency(item.rate || 0, invoice.currency), 52 + W * 0.65, y + 6, { width: 60, align: 'right' })
                .text(formatCurrency((item.qty || 1) * (item.rate || 0), invoice.currency), 52 + W * 0.8, y + 6, { width: W * 0.18, align: 'right' });
            y += 22;
        });

        if (!items.length) {
            doc.rect(40, y, W, 28).fill('#FAFAFA').stroke(BORDER);
            doc.fontSize(9).fillColor(MUTED).font('Helvetica')
                .text('No line items', 40, y + 9, { width: W, align: 'center' });
            y += 28;
        }

        y += 10;

        // ── Totals ──
        const totalsX = 40 + W * 0.56;
        const totalsW = W * 0.44;

        const totRows = [
            ['Subtotal', formatCurrency(invoice.subtotal, invoice.currency)],
            [`GST (${invoice.tax_rate || 18}%)`, formatCurrency(invoice.tax_amount, invoice.currency)],
        ];
        totRows.forEach(([label, val]) => {
            doc.fontSize(9).fillColor(MID).font('Helvetica').text(label, totalsX, y);
            doc.fontSize(9).fillColor(DARK).font('Helvetica-Bold').text(val, totalsX, y, { width: totalsW, align: 'right' });
            y += 18;
        });

        // Total line
        doc.rect(totalsX, y - 4, totalsW, 28).fill(DARK);
        doc.fontSize(11).fillColor('#FFFFFF').font('Helvetica-Bold').text('TOTAL', totalsX + 8, y + 5);
        doc.fontSize(11).fillColor(AMBER).font('Helvetica-Bold')
            .text(formatCurrency(invoice.total, invoice.currency), totalsX, y + 5, { width: totalsW - 8, align: 'right' });
        y += 36;

        // Paid stamp if applicable
        if (invoice.status === 'paid') {
            doc.save();
            doc.translate(doc.page.width / 2, y - 10).rotate(-15);
            doc.rect(-60, -18, 120, 36).fill('none').strokeColor(GREEN).lineWidth(2).stroke();
            doc.fontSize(20).fillColor(GREEN).font('Helvetica-Bold').text('PAID', -30, -10);
            doc.restore();
            y += 30;
        }

        // ── Notes ──
        if (invoice.notes) {
            y += 8;
            y = sectionTitle(doc, 'Notes', y);
            doc.rect(40, y, W, 50).fill(BG_LIGHT).stroke(BORDER);
            doc.fontSize(9).fillColor(MID).font('Helvetica').text(invoice.notes, 52, y + 8, { width: W - 24 });
            y += 58;
        }

        // ── Academy details footer ──
        y = Math.max(y + 20, doc.page.height - 160);
        doc.rect(40, y, W, 60).fill(BG_LIGHT).stroke(BORDER);
        doc.fontSize(9).fillColor(DARK).font('Helvetica-Bold').text(academy?.name || '', 52, y + 8);
        const details = [
            academy?.settings?.address,
            academy?.settings?.phone ? `Ph: ${academy.settings.phone}` : null,
            academy?.settings?.gst_number ? `GSTIN: ${academy.settings.gst_number}` : null,
        ].filter(Boolean);
        doc.fontSize(8).fillColor(MID).font('Helvetica').text(details.join('  ·  ') || '', 52, y + 22, { width: W - 24 });
        if (invoice.payment_ref) {
            doc.fontSize(8).fillColor(GREEN).text(`Payment Ref: ${invoice.payment_ref}`, 52, y + 38);
        }

        drawFooter(doc, 1, 1);
        doc.end();
    });
}

// ─── STUDENT PROGRESS REPORT PDF ─────────────────────────────────────────────
async function generateStudentReportPDF(data) {
    const { student, academy, stats, ratingHistory, recentGames, puzzleStats, attendanceSummary, period } = data;

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margins: { top: 100, bottom: 60, left: 40, right: 40 } });
        const buffers = [];
        doc.on('data', d => buffers.push(d));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        const W = doc.page.width - 80;

        drawHeader(doc, academy, 'STUDENT PROGRESS REPORT', period || formatDate(new Date()));

        let y = 100;

        // ── Student info ──
        doc.rect(40, y, W, 70).fill(BG_LIGHT).stroke(BORDER);

        doc.fontSize(14).fillColor(DARK).font('Helvetica-Bold').text(student?.name || '—', 52, y + 10);
        doc.fontSize(9).fillColor(MUTED).font('Helvetica').text(student?.email || '', 52, y + 28);
        if (student?.phone) doc.text(`Phone: ${student.phone}`, 52, y + 42);

        // Rating box top-right
        const ratingX = 40 + W - 110;
        doc.rect(ratingX, y + 8, 100, 54).fill(DARK);
        doc.fontSize(9).fillColor(MUTED).font('Helvetica').text('CURRENT RATING', ratingX + 4, y + 14, { width: 92, align: 'center' });
        doc.fontSize(24).fillColor(AMBER).font('Helvetica-Bold').text(String(student?.rating || 1200), ratingX + 4, y + 27, { width: 92, align: 'center' });

        y += 82;

        // ── KPI boxes ──
        y = sectionTitle(doc, 'Performance Summary', y);
        const kpis = [
            { label: 'Games Played', value: String(stats?.gamesPlayed || 0), sub: `${stats?.wins || 0}W / ${stats?.losses || 0}L` },
            { label: 'Win Rate', value: `${stats?.winRate || 0}%`, sub: `vs ${stats?.gamesPlayed || 0} games` },
            { label: 'Puzzles Solved', value: String(puzzleStats?.solved || 0), sub: `${puzzleStats?.accuracy || 0}% accuracy` },
            { label: 'Attendance', value: `${attendanceSummary?.rate || 0}%`, sub: `${attendanceSummary?.present || 0} / ${attendanceSummary?.total || 0} classes` },
        ];
        const boxW = (W - 18) / 4;
        kpis.forEach((k, i) => {
            const bx = 40 + i * (boxW + 6);
            doc.rect(bx, y, boxW, 56).fill('#FFFFFF').stroke(BORDER);
            doc.rect(bx, y, boxW, 4).fill(AMBER);
            doc.fontSize(18).fillColor(DARK).font('Helvetica-Bold').text(k.value, bx + 4, y + 12, { width: boxW - 8, align: 'center' });
            doc.fontSize(8).fillColor(MUTED).font('Helvetica').text(k.label, bx + 4, y + 34, { width: boxW - 8, align: 'center' });
            doc.fontSize(7.5).fillColor(MID).text(k.sub, bx + 4, y + 45, { width: boxW - 8, align: 'center' });
        });
        y += 68;

        // ── Rating history as ASCII-style sparkline ──
        if (ratingHistory?.length > 1) {
            y = sectionTitle(doc, 'Rating Progression', y);
            doc.rect(40, y, W, 80).fill('#FFFFFF').stroke(BORDER);

            const ratings = ratingHistory.map(r => r.rating);
            const minR = Math.min(...ratings) - 20;
            const maxR = Math.max(...ratings) + 20;
            const chartW = W - 80, chartH = 60;
            const cx = 60, cy = y + 10;

            // Grid lines
            [0, 0.25, 0.5, 0.75, 1].forEach(pct => {
                const gy = cy + chartH - pct * chartH;
                doc.moveTo(cx, gy).lineTo(cx + chartW, gy).strokeColor(BORDER).lineWidth(0.5).stroke();
                doc.fontSize(7).fillColor(MUTED).text(String(Math.round(minR + pct * (maxR - minR))), 40, gy - 4, { width: 18, align: 'right' });
            });

            // Line chart
            const pts = ratings.map((r, i) => ({
                x: cx + (i / (ratings.length - 1)) * chartW,
                y: cy + chartH - ((r - minR) / (maxR - minR)) * chartH,
            }));

            doc.moveTo(pts[0].x, pts[0].y).strokeColor(AMBER).lineWidth(2);
            pts.slice(1).forEach(p => doc.lineTo(p.x, p.y));
            doc.stroke();

            // Dots
            pts.forEach(p => {
                doc.circle(p.x, p.y, 2.5).fill(AMBER);
            });

            // Start / end labels
            doc.fontSize(8).fillColor(DARK).font('Helvetica-Bold')
                .text(String(ratings[0]), pts[0].x - 5, cy + chartH + 4)
                .text(String(ratings[ratings.length - 1]), pts[pts.length - 1].x - 10, cy + chartH + 4);

            y += 92;
        }

        // ── Recent games ──
        if (recentGames?.length) {
            y = sectionTitle(doc, 'Recent Games', y);

            // Table header
            doc.rect(40, y, W, 20).fill(DARK);
            ['Opponent', 'Color', 'Result', 'Rating Δ', 'Date'].forEach((h, i) => {
                const colX = [52, 52 + W * 0.38, 52 + W * 0.52, 52 + W * 0.65, 52 + W * 0.8];
                doc.fontSize(8).fillColor('#FFFFFF').font('Helvetica-Bold').text(h, colX[i], y + 6);
            });
            y += 20;

            recentGames.slice(0, 6).forEach((g, idx) => {
                const rowBg = idx % 2 === 0 ? '#FFFFFF' : BG_LIGHT;
                doc.rect(40, y, W, 20).fill(rowBg).stroke(BORDER);
                const isWhite = g.white_player_id === student.id;
                const isWin = (g.result?.winner === 'white' && isWhite) || (g.result?.winner === 'black' && !isWhite);
                const isLoss = (g.result?.winner === 'white' && !isWhite) || (g.result?.winner === 'black' && isWhite);
                const delta = isWhite ? g.white_rating_change : g.black_rating_change;

                doc.fontSize(9).fillColor(DARK).font('Helvetica')
                    .text(isWhite ? (g.black_name || '—') : (g.white_name || '—'), 52, y + 5, { width: W * 0.35 })
                doc.fontSize(8).fillColor(MUTED)
                    .text(isWhite ? '⬜ White' : '⬛ Black', 52 + W * 0.38, y + 5)
                doc.fontSize(9).fillColor(isWin ? GREEN : isLoss ? RED : MID).font('Helvetica-Bold')
                    .text(isWin ? 'Win' : isLoss ? 'Loss' : 'Draw', 52 + W * 0.52, y + 5)
                if (delta !== undefined && delta !== null) {
                    doc.fontSize(9).fillColor(delta >= 0 ? GREEN : RED).font('Helvetica-Bold')
                        .text((delta >= 0 ? '+' : '') + delta, 52 + W * 0.65, y + 5);
                }
                doc.fontSize(8).fillColor(MUTED).font('Helvetica')
                    .text(formatDate(g.created_at), 52 + W * 0.8, y + 5);
                y += 20;
            });
            y += 8;
        }

        // ── Puzzle performance ──
        if (puzzleStats) {
            y = sectionTitle(doc, 'Tactics & Puzzles', y);
            doc.rect(40, y, W, 50).fill(BG_LIGHT).stroke(BORDER);

            const pRows = [
                ['Total Attempted', puzzleStats.attempted || 0],
                ['Correctly Solved', puzzleStats.solved || 0],
                ['Accuracy', `${puzzleStats.accuracy || 0}%`],
                ['Avg Time', puzzleStats.avgTime ? `${(puzzleStats.avgTime / 1000).toFixed(1)}s` : '—'],
            ];
            pRows.forEach(([label, val], i) => {
                const px = 52 + Math.floor(i / 2) * (W / 2);
                const py = y + 8 + (i % 2) * 20;
                doc.fontSize(8).fillColor(MUTED).font('Helvetica').text(label + ':', px, py);
                doc.fontSize(9).fillColor(DARK).font('Helvetica-Bold').text(String(val), px + 110, py);
            });
            y += 58;
        }

        // ── Attendance ──
        if (attendanceSummary) {
            y = sectionTitle(doc, 'Attendance', y);
            doc.rect(40, y, W, 36).fill('#FFFFFF').stroke(BORDER);

            const attRate = attendanceSummary.rate || 0;
            const barColor = attRate >= 75 ? GREEN : attRate >= 50 ? AMBER : RED;
            const barW = Math.round((W - 120) * attRate / 100);

            doc.fontSize(9).fillColor(DARK).font('Helvetica-Bold')
                .text(`${attRate}%`, 52, y + 12, { width: 40, align: 'right' });
            doc.rect(100, y + 10, W - 120, 14).fill(BG_LIGHT).stroke(BORDER);
            doc.rect(100, y + 10, barW, 14).fill(barColor);
            doc.fontSize(8).fillColor(MUTED).font('Helvetica')
                .text(`${attendanceSummary.present || 0} present, ${attendanceSummary.absent || 0} absent out of ${attendanceSummary.total || 0} classes`, 102, y + 26);
            y += 44;
        }

        drawFooter(doc, 1, 1);
        doc.end();
    });
}

module.exports = { generateInvoicePDF, generateStudentReportPDF };